{"name": "test_login[case2]", "status": "broken", "statusDetails": {"message": "KeyError: 'email'", "trace": "case = {'expected_code': 401, 'password': 'wrongpass', 'username': 'wronguser'}\n\n    @pytest.mark.parametrize(\"case\", load_login_test_data())\n    def test_login(case):\n>       email = case[\"email\"]\nE       KeyError: 'email'\n\ntests\\test_user_api.py:14: KeyError"}, "parameters": [{"name": "case", "value": "{'username': 'wronguser', 'password': 'wrongpass', 'expected_code': 401}"}], "start": 1750067252496, "stop": 1750067252496, "uuid": "5f374484-8a20-42fe-be9d-7ba32872d3dc", "historyId": "f947d87b2a907fee868a03e1a3ba64a7", "testCaseId": "06f779fb0e10d96f86b9baeaedc8c8e5", "fullName": "tests.test_user_api#test_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_api"}, {"name": "host", "value": "ISS"}, {"name": "thread", "value": "16164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_api"}]}